{"eager.core": ["python.pywrap_tfe.TFE_Py_RegisterFallbackExceptionClass", "python.pywrap_tfe.TFE_Py_RegisterExceptionClass"], "eager.core._status_to_exception": ["framework.errors.exception_type_from_error_code", "framework.errors.UnknownError"], "framework.errors.exception_type_from_error_code": [], "framework.errors.UnknownError": [], "eager.core._NotOkStatusException.__init__": ["<builtin>.super"], "<builtin>.super": [], "eager.core._NotOkStatusException.__str__": ["framework.errors.UnknownError"], "python.pywrap_tfe.TFE_Py_RegisterExceptionClass": [], "python.pywrap_tfe.TFE_Py_RegisterFallbackExceptionClass": []}