{"eager.core": ["python.pywrap_tfe.TFE_Py_RegisterExceptionClass", "python.pywrap_tfe.TFE_Py_RegisterFallbackExceptionClass"], "eager.core._status_to_exception": ["framework.errors.UnknownError", "framework.errors.exception_type_from_error_code"], "framework.errors.exception_type_from_error_code": [], "framework.errors.UnknownError": [], "eager.core._NotOkStatusException.__init__": ["<builtin>.super"], "<builtin>.super": [], "eager.core._NotOkStatusException.__str__": ["eager.core._status_to_exception"], "python.pywrap_tfe.TFE_Py_RegisterExceptionClass": [], "python.pywrap_tfe.TFE_Py_RegisterFallbackExceptionClass": []}